### ISSUE TITLE
[Legitimate Site Blocked] beta.marginly.com

### ISSUE THREAD

**Issue by Veniamin** [phishfort/phishfort-lists#1071]
Dear MetaMask Team,

I'm writing to address an issue regarding our website, https://beta.marginly.com/, being wrongly flagged as deceptive by MetaMask. Marginly is a legitimate project dedicated to providing secure decentralized spot leverage trading. We have undergone a thorough audit with Quantstamp (https://github.com/eq-lab/marginly/blob/main/audit/Quantstamp-marginly-final-report.pdf), emphasizing our commitment to security and ethical practices.

The warning is causing unwarranted harm to our reputation. We'd like to clarify:

Fake Versions of MetaMask: We've never promoted fake MetaMask versions. Marginly operates independently and respects intellectual property.

Secret Recovery Phrase or Password Theft: Marginly does not engage in such activities and prioritizes user data security.

Malicious Transactions: Our platform ensures secure financial transactions, transparent and consensual, with robust security measures in place.

We value MetaMask's role in Ethereum's security and request a review of our site classification to remove the deceptive warning. If needed, we're ready to provide additional information or cooperate for verification.

We eagerly await your response and appreciate your attention to this matter. For queries or more details, please contact us at (contact information).

Sincerely,
Marginly team

**Comment by javierpignata** [comment]
Hi!

Thanks for reaching out.

We have removed your site from our blacklist.

Kind regards.
