### ISSUE TITLE
[Urgent] [Legitimate Site Blocked] ozys.work. 

### ISSUE THREAD

**Issue by Jongsic** [phishfort/phishfort-lists#1094]
I am writing about the issue where `ozys.work` is being incorrectly flagged as a malicious site by Metamask.

OZYS ( https://ozys.io ) is a 5-year-old blockchain technology company based in South Korea.

`ozys.work` is a domain used by our developers to test our defi products we are developing.

This domain is ONLY used for internal purposes, to deploy products developed by the our in-house developers and test them with QA. 

So it is not open to regular users, so you would not be able to access it either.

Our developers are experiencing inconvenience in their work since the ALL internal subdomain of `ozys.work` has been flagged.

Please understand that `ozys.work` is a simple internal site, and we kindly request a review of our site classification to remove the warning.

We has been also actively facing various phishing sites, even including impersonating our products, over the past five years as Metamask and you. We highly value your role in this regard.

If needed, we're ready to provide additional information or assist with verification. 

You can refer to my Github account to confirm our long-standing and legitimate presence in the blockchain industry, where we have been developing various DeFi services.

We look forward to your response and appreciate your attention.

Thank you.

**Comment by delt0** [comment]
Hello @Jongsic, nice to e-meet you

Thank you for bringing this to our attention, I will remove your site from our lists.

Please allow some time for the changes to take effect and let me know if the issue persists.

Kind regards,

**Comment by Jongsic** [comment]
Hello @delt0, 

Thank you very much for the quick response. I hope the issue is resolved quickly.

Regards,

**Comment by Jongsic** [comment]
Thank you for your kind supports!

https://github.com/phishfort/phishfort-lists/commit/82117317a94d2f57382c334eaf5d6436c84f7e3b
