### ISSUE TITLE
[Legitimate Site Blocked] bixos.estate

### ISSUE THREAD

**Issue by mrnasil** [phishfort/phishfort-lists#1117]
https://bixos.estate/panel

**Comment by shrestha-milann** [comment]
Hi,

We have removed the domain from the blacklist. It will take a few minutes
to reflect to the browsers. If the issue persists, let us know.

Warm Regards,

Milan Shrestha

Anti-Phishing Operations

***@***.***

phishfort.com <https://www.phishfort.com/>

<https://www.linkedin.com/company/phishfort/>   <https://t.me/phishfort>
<https://twitter.com/PhishFort>
