### ISSUE TITLE
[Legitimate Site Blocked] airdrop.blur.foundation

### ISSUE THREAD

**Issue by BTCAlchemist** [phishfort/phishfort-lists#1126]
https://airdrop.blur.foundation/

**Comment by shrestha-milann** [comment]
The issue has been resolved. Please clear the browser cache. Thanks
Warm Regards,

Milan Shrestha

Anti-Phishing Operations

***@***.***

phishfort.com <https://www.phishfort.com/>

<https://www.linkedin.com/company/phishfort/>   <https://t.me/phishfort>
<https://twitter.com/PhishFort>
