### ISSUE TITLE
[Legitimate Site Blocked] gray.market

### ISSUE THREAD

**Issue by LFerronato** [phishfort/phishfort-lists#1141]
https://gray.market

I don't really know why our website was added as a blacklist.

Any information that is necessary, we can make available.

**Comment by shrestha-milann** [comment]
Hello Lucas,

Kindly reach out to ***@***.*** via email to address the current
matter. Alternatively, you can provide your official email, and we will
contact you directly. Thank you.

Warm Regards,

Milan Shrestha

Anti-Phishing Operations

***@***.***

phishfort.com <https://www.phishfort.com/>

<https://www.linkedin.com/company/phishfort/>   <https://t.me/phishfort>
<https://twitter.com/PhishFort>
