### ISSUE TITLE
[Legitimate Site Blocked] noah.ovh

### ISSUE THREAD

**Issue by noahcoolboy** [phishfort/phishfort-lists#1155]
noah.ovh is literally my own website and it somehow ended up as a fraudulent website
I don't know how, considering it does not even have any mention of ethereum or cryptocurrency
Please unblock my website

**Comment by Tmaluleka07** [comment]
Hello Noah,

Thanks for reaching out. Apologies for this incident. The domain will be
removed from the blacklist. Please assist us with removing content found
here as it impersonating our client's website (find the attached
image below). Thank you.

Best regards

**Comment by noahcoolboy** [comment]
Hi, thank you for the quick response.
It does not seem like any image has been provided, or github does not seem to display it.
Would you mind providing a url to the image?

**Comment by Tmaluleka07** [comment]
Hello,

This is the url: https://noah.ovh/gemo.php

Thanks,
Best regards

**Comment by noahcoolboy** [comment]
Hello again

I believe this is a simple misunderstanding.
I will describe the situation:

This login page, which is hosted on my website, is a tool that I have developed.
It's a tool which I developed for school and friends, and it allows you to calculate your scores averages in an instant.
It is reliant on [Smartschool](https://smartschool.be), a platform used by many Belgian schools to manage students, grades, and a whole bunch of other stuff.
For technical reasons, the code behind this tool fetches the [real login page](https://olvrode.smartschool.be) and prompts it to the user.
Once the user logs in, the tool automatically logs into the user's account and fetches their scores, to calculate the student's averages and displays it. No credentials are being stored and cookies are being discarded once everything has been calculated.
The page was never meant as a phishing page, but instead was out of necessity. I was not able to gain an oauth token from the platform to easily authenticate the user legitimately, which is why I had to resort to using the user's login details.
I had no harmful intentions when creating this page, and it was a simple tool meant to improve student's lives.

I had changed the login page logo to my website to make it clear that it was not an official smartschool page, and recently added a banner too to make it even more clear. Which other measures should I have to take as to get this website unblocked? It's not meant for phishing, but as a utility.

**Comment by Tmaluleka07** [comment]
Hello Noah,

The site has copied and used smartschool's logo and name to provide a fake
relationship with our client, creating confusion for
smartschool's customers/users and therefore harming the business of our
client. Our client is not related to nor does it have any affiliation to
your website and the website is being used without smartschool's permission
hence the removal request.

Your site has been removed from the blacklist, could you please remove the
infringing content. Thank you.

Best regards

**Comment by noahcoolboy** [comment]
Hello again,

Thank you for having removed my website from the blacklist.
I will be removing smartschool logo and colors as to avoid confusion with the real website.
In addition, I have added a clear red banner mentioning the fact that it is not a real nor official version of the website.
I have contacted Smartschool as to come to a solution and avoid any future disputes.

Best regards
Noah
