### ISSUE TITLE
[Legitimate Site Blocked] Replit.dev subdomains

### ISSUE THREAD

**Issue by TABASCOatw** [phishfort/phishfort-lists#1175]
It seems as though replit subdomains (such as https://3b4589ca-9b35-4fd6-8ccc-deaad4f88277-00-nd5i58a4z8gw.riker.replit.dev) are being mass flagged as deceptive. Replit.dev (and replit.app) are domains for apps hosted through replit (like vercel) and thus shouldn't be blocked given the volume of developer-oriented applications hosted within temporary replit.dev domains.

**Comment by delt0** [comment]
Hello, thanks for bringing this to our attention.

We have removed it from our lists, please allow some time to changes impact.

Kind regards,
