### ISSUE TITLE
[Legitimate Sites Blocked] replit.dev and replit.app

### ISSUE THREAD

**Issue by edgarhernandezch** [phishfort/phishfort-lists#1179]
Hello,

I'm Edgar Hernandez, I tackle abuse, and trust and safety at Replit.

A number of our users are reporting that our replit.dev and replit.app domains are being blocked and flagged as malicious by y'all. We've also noticed a few users flagging issues in the repo related to this: https://github.com/phishfort/phishfort-lists/issues/1176

We'd like to have those domains moved to the allow list and are happy to help make that happen. 

Thank you!
Edgar

**Comment by delt0** [comment]
Hello @edgarhernandezch, nice to e-meet you!

I added both domains to our whitelist two days ago. Could you confirm if the issue persists?

Keep in touch.

Best regards,

**Comment by edgarhernandezch** [comment]
@delt0 thanks for the speedy response! I don’t see it in this list though? https://github.com/phishfort/phishfort-lists/blob/master/whitelists/domains.json

**Comment by delt0** [comment]
@edgarhernandezch That list has not been in use for some time and will be deprecated shortly. I have added your domains internally.

If possible, please let us know if you have any blacklisting notices after January 24 to confirm everything is fine.

**Comment by edgarhernandezch** [comment]
@delt0 thanks again and sounds good, I'll reach out if any issues persist.

**Comment by edgarhernandezch** [comment]
@delt0, I just re-analyzed the URL replit.dev and VirusTotal is still flagging it as Malicious via PhishFort. Any ideas? https://www.virustotal.com/gui/url/2e480bc457c6da7dd1539b7828e3cb1de75dc28a3655846020374bd031d7eabf?nocache=1

**Comment by delt0** [comment]
Hello @edgarhernandezch! I'll remove that flag on VirusTotal right now - it will be reflected in short time. Do you want to provide us with some means of direct contact with you in case any future situation arises? We will be happy to help and work together on whatever is needed.

**Comment by edgarhernandezch** [comment]
Hey @delt0! Thanks so much! Yes please feel free to email me at edgar at replit dot com and/or abuse at replit dot com. Very much appreciate your help

**Comment by edgarhernandezch** [comment]
@delt0 , just confirmed we are no longer being flagged as malicious by PhishFort. Thanks so much!

**Comment by delt0** [comment]
My pleasure, @edgarhernandezch. Let me know if I can be of help with anything else
