### ISSUE TITLE
hebeswap.com blacklisted???

### ISSUE THREAD

**Issue by HebeBlock** [phishfort/phishfort-lists#13]
Hi, 
some users reported to us today that our website has been blacklisted,
we don't know what happened to get into the list。
https://twitter.com/BlockHebe
Please check our Twitter, we are a SWAP on ETC, 
our contract has been open source, please remove us from the blacklist,
thank you

**Comment by korn101** [comment]
Sorry team, we have reviewed and reclassified. It should propagate to the blacklist shortly on our next automated update.
