### ISSUE TITLE
[Legitimate Site Blocked] mail.proton.me

### ISSUE THREAD

**Issue by aerocyber** [phishfort/phishfort-lists#1319]
https://mail.proton.me/ is the Proton mail web link. For some reason, Metamask flagged it. Please review.

**Comment by aerocyber** [comment]
status?

**Comment by shrestha-milann** [comment]
Hi there,

The concerned domain is currently not on our blacklist. You may verify from
the following link.
https://lookup.phishfort.com/api/lookup?url=mail.proton.me

Warm Regards,

Milan Shrestha

Anti-Phishing Operations

***@***.***

phishfort.com <https://www.phishfort.com/>

<https://www.linkedin.com/company/phishfort/>   <https://t.me/phishfort>
<https://twitter.com/PhishFort>

**Comment by aerocyber** [comment]
Thanks for the update. Closing this issue as it's resolved.
