### ISSUE TITLE
[Legitimate Site Blocked] prlivnote.com

### ISSUE THREAD

**Issue by osbornepeter** [phishfort/phishfort-lists#1365]
https://prlivnote.com/

False Positive - The site has nothing to do with WEB3 or metamask - I urgently demand that the site be unblocked!

**Comment by javierpignata** [comment]
Hi!

Thanks for reaching out. The site is not blocklisted by PhishFort.

Kind regards.

**Comment by osbornepeter** [comment]
The site swears at MetaMask, but when pressured to challenge it, it throws it at this Git
