### ISSUE TITLE
[Legitimate Site Blocked] cuckoo.network

### ISSUE THREAD

**Issue by larkbirdy** [phishfort/phishfort-lists#1442]
https://cuckoo.network/

**Comment by shrestha-milann** [comment]
Hi,

The aforementioned domain is not blacklisted by Phishfort. Please verify
from the following:
https://lookup.phishfort.com/api/lookup?url=cuckoo.network

WR.

Milan Shrestha

Anti-Phishing Operations

***@***.***

phishfort.com <https://www.phishfort.com/>

<https://www.linkedin.com/company/phishfort/>   <https://t.me/phishfort>
<https://twitter.com/PhishFort>

**Comment by larkbirdy** [comment]
Thanks for confirming!

The metamask's warning page's in-page link leads me here. There are multiple blocklists for metamask to work. Closing this one. Another blocklist is https://github.com/MetaMask/eth-phishing-detect/issues/88938.
