### ISSUE TITLE
illegitimate site unblocked (https://ikdhotspot.com/ww/transfer/OnPoint.com)

### ISSUE THREAD

**Issue by joejoe135791** [phishfort/phishfort-lists#162]
site https://ikdhotspot.com/ww/transfer/OnPoint.com is a fake onpoint community credit union website

**Comment by shrestha-milann** [comment]
Hello there,

Thanks for reporting to us. Will add to our Blacklist.
You can also report us from our browser extension - [Protect](https://www.phishfort.com/protect).

Regards,
