### ISSUE TITLE
[Legitimate Site Blocked] all-weather-protocol.on-fleek.app

### ISSUE THREAD

**Issue by david30907d** [phishfort/phishfort-lists#1642]
https://all-weather-protocol.on-fleek.app/

Hi I'm the founder of All Weather Protocol. Thx for creating this Phishfort list repo for keeping us safe. Especially I've been scammed for 3 times. Very grateful for this repo's contribution

But I'm wondering why my project has been flagged as a phishing website.

We're based on Thirdweb's AA wallet and bundle multiple defi transactions to implement zap-in/zap-out/rebalance features.
If you get a chance, would you give me more error msg or which packages should we remove?

**Comment by ariana-bajrami** [comment]
Hello

Thank you for reaching out to us.

I have checked and can confirm that your website is not on our blocklist.
You can confirm it at:
https://lookup.phishfort.com/api/lookup?url=all-weather-protocol.on-fleek

Regards,

**Comment by david30907d** [comment]
Hi @ariana-bajrami , thx for the prompt reply. But seems to me that metamask is still blocking my site. Is it because they need some time to update to the latest phishfort library?

https://metamask.github.io/phishing-warning/v4.0.0/#hostname=all-weather-protocol.on-fleek.app&href=https%3A%2F%2Fall-weather-protocol.on-fleek.app%2F

<img width="1120" alt="Screenshot 2024-11-09 at 22 30 00" src="https://github.com/user-attachments/assets/bf3faf6a-8a24-43b1-b92c-cfb564105e54">

**Comment by david30907d** [comment]
<img width="1230" alt="Screenshot 2024-11-10 at 8 26 04" src="https://github.com/user-attachments/assets/f8a10bdb-9233-4f81-a1b2-144d20f5a6e0">

**Comment by ariana-bajrami** [comment]
Hi,

Regarding Metamask blocklist we suggest you reach out to their support team
for faster response.

Regards,
Ariana

**Comment by david30907d** [comment]
Got it , thx for the reply
