### ISSUE TITLE
[Legitimate Site Blocked] ethdenver.linkdrop.io

### ISSUE THREAD

**Issue by Dobrokhvalov** [phishfort/phishfort-lists#176]
Hey there, I'm founder of Linkdrop and one of our subdomain is in your list for some reason - https://ethdenver.linkdrop.io/. 
Please, unblock as it causing troubles to us and our customer - EthDenver, https://www.ethdenver.com/ .

**Comment by javierpignata** [comment]
Hi, thanks for reaching out!

We have removed your site from our blacklist. Please wait for a few hours until changes propagate and try again. Let us know if the issue persists.

Kind regards.
