### ISSUE TITLE
[Legitimate Site Blocked] bridge.ton.space QR Mint is not spam

### ISSUE THREAD

**Issue by qr-mint** [phishfort/phishfort-lists#1824]
https://bridge.ton.space/bridge/events?client_id=c35fdaa01d933f0205ddffe704642d02630a72984f9f770dee13881afb06174b
You can remove my site from scam?

**Comment by javierpignata** [comment]
Hi! Thanks for reaching out to us.

Please note that the reported URL is not being flagged by PhishFort.

Kind regards.

**Comment by qr-mint** [comment]
Do you mean this PhishFort https://www.phishfort.com/?
Can I don't use PhishFort?
