### ISSUE TITLE
Conflict with tonconnect/sdk,TON Wallets

### ISSUE THREAD

**Issue by axing9409** [phishfort/phishfort-lists#1825]
![1731939673440](https://github.com/user-attachments/assets/7f4709d1-67bf-42d7-bbfa-0c36fe9207a8)
![photo_2024-11-18_22-38-51](https://github.com/user-attachments/assets/d0b65d9c-6e5e-4ccf-ba89-0c5d2b90ce44)

**Comment by javierpignata** [comment]
Hi! Thanks for reaching out to us.

Please note that the reported URL is not being flagged by Phishfort.

Kind regards.

**Comment by axing9409** [comment]
You need to see recently issues,and over 100 issues are the same.You should handle this as soon as possible,because there are many TON DApps use tonconnect!

**Comment by axing9409** [comment]
> You need to see recently issues,and over 100 issues are the same.You should handle this as soon as possible,because there are many TON DApps use tonconnect!


You need to see recently issues,and over 100 issues are the same.You should handle this as soon as possible,because there are many TON DApps use tonconnect!

**Comment by axing9409** [comment]
> > You need to see recently issues,and over 100 issues are the same.You should handle this as soon as possible,because there are many TON DApps use tonconnect!
> 
> You need to see recently issues,and over 100 issues are the same.You should handle this as soon as possible,because there are many TON DApps use tonconnect!

https://github.com/ton-connect/sdk/issues/286   did you see that?

**Comment by axing9409** [comment]
Metamask currently has a very bad reputation in the TON ecosystem. You need to check it out and resolve it as soon as possible.

**Comment by axing9409** [comment]
> > > You need to see recently issues,and over 100 issues are the same.You should handle this as soon as possible,because there are many TON DApps use tonconnect!
> > 
> > 
> > You need to see recently issues,and over 100 issues are the same.You should handle this as soon as possible,because there are many TON DApps use tonconnect!
> 
> [ton-connect/sdk#286](https://github.com/ton-connect/sdk/issues/286) did you see that?


Metamask currently has a very bad reputation in the TON ecosystem. You need to check it out and resolve it as soon as possible.

**Comment by axing9409** [comment]
？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？why close this?
