### ISSUE TITLE
[Legitimate Site Blocked] tickets.newfutures.network

### ISSUE THREAD

**Issue by decentration** [phishfort/phishfort-lists#235]
https://tickets.newfutures.network/

*How did this get on the list?*

Please remove the flag.

The site was build by httpsL//decentration.org and is legitimate.

**Comment by javierpignata** [comment]
Hi,
thanks for reaching out!

We removed the site from our blacklist. Please allow a few hours and try again. Let us know if the issue is solved.

Kind regards.

**Comment by decentration** [comment]
thanks
