### ISSUE TITLE
[Legitimate Site Blocked] arbdrop.com

### ISSUE THREAD

**Issue by donflor** [phishfort/phishfort-lists#237]
https://arbdrop.com/

Remove our site from your block list. We included the smart contract address on the site so that people can review what it does before approving the transaction. And if you check on the smart contract, all it does is transfer token from our wallet to everyone who purchased the package and nothing else. It's a basic react, web3 site - no db. Please let us know if you need us to supply anything to prove its legitimacy. 

![CleanShot 2023-01-03 at 10 48 02@2x](https://user-images.githubusercontent.com/2294054/210422497-dfab1d29-1a31-4eec-9a81-be18be48512a.png)

**Comment by javierpignata** [comment]
Hi,
thanks for reaching out!

We removed the site from our blacklist. Please allow a few hours and try again. Let us know if the issue is solved.

Kind regards.
