### ISSUE TITLE
[Legitimate Site Blocked] hb.4everland.app

### ISSUE THREAD

**Issue by Easonyule** [phishfort/phishfort-lists#240]
This is our own test environment domain name, which is only used for internal testing. We hereby protest that it was suddenly restricted. We hope it can be restored as soon as possible without affecting our normal development schedule. 4everland is a Web3 cloud computing platform that provides underlying technical support services for web3 developers. There is no transaction risk. We hope to recover as soon as possible. Thank you very much!

**Comment by javierpignata** [comment]
Hi,
Thanks for reaching out!

The site has been removed from our blacklist.

Kind regards.
