### ISSUE TITLE
[Legitimate Site Blocked] stake-codes.bz

### ISSUE THREAD

**Issue by vanecanna63** [phishfort/phishfort-lists#254]
https://stake-codes.bz/

Hello this is my website but i dont now how to remove the message from metamask list, is this really a message from metamask or maybe my website has been hacked.
![Uploading Capture d’écran 2023-01-11 à 12.25.27.png…]()

**Comment by javierpignata** [comment]
Hi! Thanks for reaching out.
It is a message from MetaMask. You should contact them to get your site removed from their blacklist.

Kind regards.

**Comment by vanecanna63** [comment]
Thank you ok i will now
have a good day

**Comment by javierpignata** [comment]
Have a nice day you too!

Kind regards.
