### ISSUE TITLE
[Legitimate Site Blocked] discord-accounts.ru

### ISSUE THREAD

**Issue by Alex-Samojlov** [phishfort/phishfort-lists#286]
Why has my message been ignored for 3 weeks now? Is the site listed as a phishing site because it violates the rules of some third-party site? What is this nonsense?

The site has been around longer than any other discord account stores and has a reputation. Why is a proven store for years on the block and other stores are not affected?

Please explain why the site has fake accusations of phishing, stealing money and data? Unblock the site, there is no danger. Check the site with any services, it is everywhere in the white lists.

![изображение](https://user-images.githubusercontent.com/121597358/213269067-3cbb6b00-928a-4059-84c6-9ab52bfa603a.png)

**Comment by Alex-Samojlov** [comment]
Account stores have been running for decades and have not been blocked by anyone. Social networks prohibit the sale of accounts, but these are just rules on their sites that cannot affect the operation of any external resources. Why did you find this particular store to be in violation?

Give a detailed answer. The site is popular and has never deceived anyone. But because of your mistake I have to change browsers, so that this fake table does not appear:
![изображение](https://user-images.githubusercontent.com/121597358/213270496-3e438f4c-d9fe-4d6c-8847-1e3ba2880720.png)

Let's solve the situation and remove the block, you will thank a lot of users.

**Comment by xtr3sor** [comment]
Issue solved.

**Comment by mmoadvert** [comment]
> Issue solved.

Virustotal still shows "Malicious"

![image](https://user-images.githubusercontent.com/75162773/220841908-c42eb5da-499e-455a-a249-e7c12476cb9e.png)
