### ISSUE TITLE
Request to remove ipfs.io from the blacklist

### ISSUE THREAD

**Issue by andyschwab** [phishfort/phishfort-lists#3]
Hi friends,

I'm reaching out on behalf of [Protocol Labs](https://protocol.ai) and the [IPFS project](https://github.com/ipfs), following up on an issue raised by one of our community members - who is also a user of PhishFort!

It looks like the entire ipfs.io domain is currently on the blacklist: https://github.com/phishfort/phishfort-lists/blob/master/blacklists/domains.json#L5856

I wonder if this is related to the gateway functionality that ipfs.io provides. I wanted to clarify how the gateway functions, and see if we can resolve this issue and have ipfs.io removed from the blacklist. From [our docs](https://docs.ipfs.io/concepts/ipfs-gateway/#who-is-responsible-for-the-content-that-is-viewed-through-the-ipfs-io-gateway):

> Users of the ipfs.io gateway are required to comply with all applicable laws and regulations while using the ipfs.io gateway.
> 
> The ipfs.io gateway is not a data storage provider or website host. The ipfs.io gateway allows users to view content hosted by third parties over which Protocol Labs exercises no control. The fact that certain content is viewable through the ipfs.io gateway does not mean it is hosted by the ipfs.io gateway or that Protocol Labs can do anything to delete that content.
> 
> As explained above, the ipfs.io gateway is not a website hosting provider or data storage provider, and Protocol Labs cannot remove material from the Internet that is accessible through the ipfs.io gateway. If you believe that material accessible through the ipfs.io gateway is illegal or violates your copyright, you are encouraged to directly notify whoever is hosting or controls that data.
> 
> While the ipfs.io gateway does not serve as a host for data or websites, in appropriate circumstances, Protocol Labs can disable the ability to view certain content via the ipfs.io gateway. This does not mean that the data itself has been taken down from the network but rather that the content is not viewable using the ipfs.io gateway. This also will not impact the availability of the data through other gateways run by other parties.
> 
> You can report abuse by emailing abuse@protocol.ai. When appropriate, we will disable access through the ipfs.io gateway to the specific content set forth in your abuse report.

We actively action reports sent to abuse@protocol.ai and can work with you to block malicious content at our gateway. That said, many organizations and teams run their [own gateways](https://ipfs.github.io/public-gateway-checker/), and local gateways are now integrated into multiple browsers including Brave and Opera.

From the standpoint of phishing prevention with regard to IPFS gateways, one solution might be to identify malicious hashes (IPFS uses [content based addressing](https://docs.ipfs.io/concepts/how-ipfs-works/#content-addressing)), allowing PhishFort to block dangerous content available on the IPFS network regardless of the gateway.

Looking forward to working with you to get this resolved! ~Andy

**Comment by Deon-Trevor** [comment]
We will put together a pipeline to use content-based addressing to blacklist malicious content on your network. We will reach out for further partnership.
