### ISSUE TITLE
[Legitimate Site Blocked] dexfix.site

### ISSUE THREAD

**Issue by ghost** [phishfort/phishfort-lists#305]
https://dexfix.site/
last week when i connect my wallet to this site i lose all my GVR coin please if possible can return my money 105$ and 40 GVR Coin to my wallet

**Comment by javierpignata** [comment]
Hi,
Thanks for reaching out and I am so sorry to hear that...

We cannot retrieve your money back, but we will do all in our hands to get this domain taken down and prevent this malicious site to scam anyone else in the future.

Kind regards.
