### ISSUE TITLE
[Legitimate Site Blocked] swap.ggachains.com

### ISSUE THREAD

**Issue by zsxueyuan** [phishfort/phishfort-lists#306]
https://swap.ggachains.com/

Ffs, over 100 client projects using the swap.ggachains.com .
Please remove the warning since it impacts our client.

**Comment by zsxueyuan** [comment]
Ffs, over 100 client projects using the swap.ggachains.com .
Please remove the warning since it impacts our client.

**Comment by javierpignata** [comment]
Hi,

Apologies for the delayed response. We have removed your site from our blacklist. Please allow some time until changes propagate and try again. Let us know if the issue is not solved.

Kind regards.
