### ISSUE TITLE
klikjer.com should be remove from the blacklist

### ISSUE THREAD

**Issue by mrshuth** [phishfort/phishfort-lists#32]
8 months ago, our website was hacked and hackers put malware code and phishing code on our website.

However, we have successfully removed the code and cleaned our website of any malware over the past 6 months.

Unfortunately, our site is still blacklisted in your database at line 25338 klikjer.com
U could visit and check our website.
Hopefully you can remove our site from your blacklist.

Thank you.

**Comment by mrshuth** [comment]
Hi!

Could my website "klikjer.com" be remove from the master blacklist?
Thanks in advance.

**Comment by xtr3sor** [comment]
Hi @mrshuth

We've removed your domain from our blacklist, it will take a few hours for the change to be pushed to our repo.

Thanks!

**Comment by mrshuth** [comment]
Tq so much! :)
