### ISSUE TITLE
[Legitimate Site Blocked] ipfs.io

### ISSUE THREAD

**Issue by Yovista** [phishfort/phishfort-lists#329]
https://ipfs.io/ipfs/QmWNdq4RNVgF6nnjK7PamMrMDCra1qC7sSsF9MY33XN8KF/

**Comment by Yovista** [comment]
It's a web-based art project where the audience will see the art changing according to ETH price. 100% There's No malicious/phising activity inside it.

**Comment by delt0** [comment]
Hello, thank you very much for letting us know about this. It will be fixed shortly.
