### ISSUE TITLE
[Legitimate Site Blocked] ipfs.io

### ISSUE THREAD

**Issue by LJ674** [phishfort/phishfort-lists#330]
https://ipfs.io/ipfs/QmWDsQX4UPvKw6J5PNNxzg3C8sVLF7imVr4qEh8Lp2sco5/index.html

This site is a file system where a video is able to be a playable nft game displayed on opensea, no wallet signature or anything needed to use/play. Please help us sort as it is an important feature of our nft on opensea and currently makes it impossible to view/play. Thanks 
You can press enter on the video to get to the game. https://opensea.io/assets/ethereum/0xa0c38108bbb0f5f2fb46a2019d7314cce38f3f22/453

**Comment by delt0** [comment]
Hello, thank you very much for letting us know about this. It will be fixed shortly.

**Comment by LJ674** [comment]
Ok thanks is there anything else we can do to prevent this happening again or to any of our other playable nft collections we have 4 total

**Comment by delt0** [comment]
We have already taken the appropriate measures so that this does not happen again
