### ISSUE TITLE
[Legitimate Site Blocked] ipfs.io

### ISSUE THREAD

**Issue by AugustDev** [phishfort/phishfort-lists#334]
https://ipfs.io/ipfs/QmXzqiXta2gmVvoqVfts79QrwY7XzvcbL8TXvPjaAqHKba/?payload=eyJoYXNoIjoiMHhiNzJmMDU4ZDZmOTVhNjIyMGI0NjQzZGU3MjI4Y2VjMjY1NWYzN2ZlYWMwZTNkYjI4MTZlYTQxYjcxOTdlNmFiIiwiZWRpdGlvbk51bWJlciI6MCwidG90YWxFZGl0aW9ucyI6MH0%3D

**Comment by delt0** [comment]
Hello, thank you very much for letting us know about this. It will be fixed shortly.
