### ISSUE TITLE
[Legitimate Site Blocked] ipfs.io

### ISSUE THREAD

**Issue by DomainDegen** [phishfort/phishfort-lists#335]
https://ipfs.io/ipfs/QmfZmKzkYFt5qkETUBrKPP7PBYG3BXu4nSJj4QzJMU2fbd/

This is my web3 site "takethecake.nft" (Unstoppable Domains) with data on IPFS
Please remove from your "blocked list" as it's completely legit.
I would like to know why I was flagged.

**Comment by delt0** [comment]
Hello, thank you very much for letting us know about this. It will be fixed shortly.
