### ISSUE TITLE
[Legitimate Site Blocked] ipfs.io

### ISSUE THREAD

**Issue by csharpner** [phishfort/phishfort-lists#336]
https://ipfs.io

This is NOT a phishing site.  It's the DEFACTO STANDARD, central core gateway between the legacy web and Web 3.0.  This is the gateway for IPFS (InterPlanetary File System).  This domain should have been the VERY FIRST one you white listed.  This is almost as bad as blocking your own domain.  IPFS & MetaMask are part of the same decentralized ecosystem and work together.

PLEASE fix this ASAP!

**Comment by delt0** [comment]
Hello, thank you very much for letting us know about this. It will be fixed shortly.
