### ISSUE TITLE
[Legitimate Site Blocked] ipfs.io (breaks OpenSea) 

### ISSUE THREAD

**Issue by AugustDev** [phishfort/phishfort-lists#337]
https://opensea.io/assets/ethereum/0x708f94690076b08fa24e60c01a85054350dbcfc2/850566621

 
<img width="1883" alt="image" src="https://user-images.githubusercontent.com/5672094/215338322-8019f6a9-3110-4db0-96ea-b41e4da389f3.png">

**Comment by delt0** [comment]
Hello, thank you very much for letting us know about this. It will be fixed shortly.
