### ISSUE TITLE
[Legitimate Site Blocked] ipfs.io

### ISSUE THREAD

**Issue by mrbub1** [phishfort/phishfort-lists#341]
https://ipfs.io/ipfs/QmX4nfgA35MiW5APoc4P815hMcH8hAt7edi5H3wXkFm485/2407.html

**Comment by mrbub1** [comment]
This only happens in web extension. Mobile is working as per usual

**Comment by delt0** [comment]
Hello, thank you very much for letting us know about this. It will be fixed shortly.

**Comment by mrbub1** [comment]
Thank you, how long will it take?

**Comment by delt0** [comment]
It was already removed a few hours ago. You shouldn't have any problems right now, if so please let us know
