### ISSUE TITLE
[Legitimate Site Blocked] ipfs.io

### ISSUE THREAD

**Issue by SCGPhotographer** [phishfort/phishfort-lists#343]
https://ipfs.io/ipfs/bafybeibivxcg4mpkewcu77iiqirlyrwxgcqi4sbsxaqbyxqis4opbnxnky

Hello, this domain it is the IPFS domain of the image of one of my NFTs and I don't understand why it is flagged as phishing domain. All the images of my nfts are flagged... This is not a phishing domain, it is just one of my photos...

Please, can you help me solve the problem?

Greetings, 
Sorin

**Comment by delt0** [comment]
Hello, thank you very much for letting us know about this. It will be fixed shortly.
