### ISSUE TITLE
[Legitimate Site Blocked] human-hippo.vercel.app

### ISSUE THREAD

**Issue by JenAprlrain** [phishfort/phishfort-lists#346]
https://human-hippo.vercel.app/home.html

This is just a simple NFT minting site there is no phishing scam or any collecting of private keys.

**Comment by JenAprlrain** [comment]
We had to move to a different domain but are worried that our new domain will get flagged as it is the same website. Please let me know what the issue is because this is just a NFT minting site that interacts with a blockchain smart contract.

**Comment by javierpignata** [comment]
Hi,

We have removed the site from your blacklist. Please allow some time until changes propagate.

Kind regards.

**Comment by JenAprlrain** [comment]
do you know the reason why it was getting flagged? I am curious as I would like to avoid any future projects from getting flagged like this.

**Comment by javierpignata** [comment]
Hi Jen,

It was reported as a phishing site by a third party through our plugin.

Kind regards.

**Comment by JenAprlrain** [comment]
ok thank you

**Comment by JenAprlrain** [comment]
we have a suspicion that 2 people that are reporting us for no reason is there anything that we can do to prevent false reporting? Is there a way to pre-register for a white listing or something?
