### ISSUE TITLE
[Legitimate Site Blocked] sweetaccounts.cc

### ISSUE THREAD

**Issue by Manuelucki** [phishfort/phishfort-lists#476]
https://sweetaccounts.cc/

My account shop is being flagged as a phishing for no reason.
I don't understand.

**Comment by javierpignata** [comment]
Hi, remove this please:
![image](https://user-images.githubusercontent.com/96588126/222922654-fd56fd0e-053b-475f-87d9-d51be691aeb9.png)

**Comment by Manuelucki** [comment]
> Hi, remove this please: ![image](https://user-images.githubusercontent.com/96588126/222922654-fd56fd0e-053b-475f-87d9-d51be691aeb9.png)

Removed.

**Comment by javierpignata** [comment]
Thanks!
The website was removed from our blacklist. Please allow some time until changes propagate. Let us know if the issue is not solved.

Regards.
