### ISSUE TITLE
[Legitimate Site Blocked] www.projectrxnegade.com

### ISSUE THREAD

**Issue by renshawdev** [phishfort/phishfort-lists#521]
https://www.projectrxnegade.com/
See https://github.com/MetaMask/eth-phishing-detect/pull/12022

I am the developer of this site. 
The site has no user analytics, does NOT capture any personal information, does NOT trigger any malicious transactions.

Not sure why it was added. Maybe @dubstard can provide a reason?

**Comment by shrestha-milann** [comment]
Hi Paul,

The domain in question is not blacklisted by us.
If it's still flagged by PhishFort at your end, please send a screenshot of
the warning banner so we can investigate further.

Thanks and Regards,
--

Milan Shrestha

Anti-Phishing Operations

***@***.***

phishfort.com <https://www.phishfort.com/>

<https://www.linkedin.com/company/phishfort/>   <https://t.me/phishfort>
<https://twitter.com/PhishFort>

**Comment by renshawdev** [comment]
Hi,

Sorry, there must be a link somewhere that points to here. I'll try to find it again and report the link. 

Have raised an issue on the correct metamask repo now.

Thanks for the quick response :)
