### ISSUE TITLE
[Legitimate Site Blocked] games.gala.com

### ISSUE THREAD

**Issue by Deathlicious** [phishfort/phishfort-lists#592]
https://games.gala.com/

**Comment by shrestha-milann** [comment]
Hi,

Sorry for the inconvenience.
We have processed removing the domain from the blocklist. It will take a
few minutes to reflect.
If the issue persists, let us know.

Thanks and Regards,
--

Milan Shrestha

Anti-Phishing Operations

***@***.***

phishfort.com <https://www.phishfort.com/>

<https://www.linkedin.com/company/phishfort/>   <https://t.me/phishfort>
<https://twitter.com/PhishFort>
