### ISSUE TITLE
[Legitimate Site Blocked] bafybeido3gs75i4ous3ha55ceqxsjokgsbdimuc6nr7wymrciamdybudui.ipfs.nftstorage.link

### ISSUE THREAD

**Issue by dima-brook** [phishfort/phishfort-lists#600]
https://bafybeido3gs75i4ous3ha55ceqxsjokgsbdimuc6nr7wymrciamdybudui.ipfs.nftstorage.link/54.png

**Comment by Deon-Trevor** [comment]
``https://lookup.phishfort.com/api/lookup?domain=ipfs.nftstorage.link``

This is not in our blacklist
