### ISSUE TITLE
[Legitimate Site Blocked] bafkreic4nej4jelxwlrwa7r44g52ckuot3dwejpysjcnjxnymd2zculzxi.ipfs.nftstorage.link

### ISSUE THREAD

**Issue by mariospeterman** [phishfort/phishfort-lists#613]
https://bafkreic4nej4jelxwlrwa7r44g52ckuot3dwejpysjcnjxnymd2zculzxi.ipfs.nftstorage.link/

**Comment by Deon-Trevor** [comment]
``https://lookup.phishfort.com/api/lookup?domain=ipfs.nftstorage.link``

This is not in our blacklist
