### ISSUE TITLE
[Legitimate Site Blocked] bafybeiebpplbop5xfxx4ufndvhdyo6zonhmwjep67ke3f3sxdc6wyktwti.ipfs.nftstorage.link

### ISSUE THREAD

**Issue by xrpdevs** [phishfort/phishfort-lists#619]
https://bafybeiebpplbop5xfxx4ufndvhdyo6zonhmwjep67ke3f3sxdc6wyktwti.ipfs.nftstorage.link/1.json

Why is this being blocked?

NFT.storage is just an IPFS gateway??

**Comment by Deon-Trevor** [comment]
``
https://lookup.phishfort.com/api/lookup?domain=ipfs.nftstorage.link
https://lookup.phishfort.com/api/lookup?domain=nftstorage.link
``

This is not blocked, not by us.
