### ISSUE TITLE
[Legitimate Site Blocked] pancakesquads.com

### ISSUE THREAD

**Issue by mviils** [phishfort/phishfort-lists#644]
https://pancakesquads.com/

**Comment by Deon-Trevor** [comment]
The legitimate project is here: 

https://twitter.com/pancakesquadnft
https://pancakeswap.finance/pancake-squad
https://pancakeswap.finance/nfts

**Comment by mviils** [comment]
we'll ask to update https://twitter.com/pancakesquadnft the info to bio, would that be sufficient?

**Comment by Deon-Trevor** [comment]
> we'll ask to update https://twitter.com/pancakesquadnft the info to bio, would that be sufficient?

Have the team reach out to us on the "War Room" and we'll resolve the issue
