### ISSUE TITLE
[Legitimate Site Blocked] www.etherspay.com

### ISSUE THREAD

**Issue by rayorole** [phishfort/phishfort-lists#661]
https://www.etherspay.com/

**Comment by shrestha-milann** [comment]
Hi,

The mentioned site is not blocked by us.

Thanks and Regards,
--

Milan Shrestha

Anti-Phishing Operations

***@***.***

phishfort.com <https://www.phishfort.com/>

<https://www.linkedin.com/company/phishfort/>   <https://t.me/phishfort>
<https://twitter.com/PhishFort>
