### ISSUE TITLE
[Legitimate Site Blocked] 88f1-176-106-253-139.ngrok-free.app

### ISSUE THREAD

**Issue by GEOEGII555** [phishfort/phishfort-lists#672]
https://88f1-176-106-253-139.ngrok-free.app/inspect/http
It was my ngrok app
Ofc it could be a malicious site before (because IDs are rotated and given to different ppl) but fix it pls

**Comment by javierpignata** [comment]
Hi!
Thanks for reaching out, but the site is not blacklisted by us.

Kind regards.
