### ISSUE TITLE
[Legitimate Site Blocked] www.blogspot.com

### ISSUE THREAD

**Issue by hiiro74** [phishfort/phishfort-lists#723]
not sure why this was added to your list but its a legitimate site that redirects to www.blogger.com

**Comment by hiiro74** [comment]
It has been over a month since I opened this issue and its still not being addressed.

**Comment by hiiro74** [comment]
Its already 2 months and still no update on this. I know blogspot has alot dangerous sites but blocking their main site www.blogspot.com is not really helping those with legitimate sites on their platform.

**Comment by javierpignata** [comment]
Hi,

The site is not blacklisted by us.

Kind regards.

**Comment by hiiro74** [comment]
Its listed in your blacklist/domains.json line 2610
https://raw.githubusercontent.com/phishfort/phishfort-lists/master/blacklists/domains.json

Below is a screenshot from my browser.
[https://i.imgur.com/QYs4nfr.png](url)

So can you still say its not being blacklisted by you.

**Comment by javierpignata** [comment]
Hi,

We removed www.blogspot.com from our blacklist.

Please allow some time until changes propagate.

Kind regards.

**Comment by hiiro74** [comment]
ok will check after 2 days.

**Comment by hiiro74** [comment]
well its still being blocked and its still listed in your blacklists/domains.json file (line: 79894)
I already tried to reinstall the browser I use and its still the same.
https://i.imgur.com/C1Idxys.png

**Comment by javierpignata** [comment]
Hi Hiiro,

Apologies for the misunderstanding. It seems the FQDN wasn't fully removed. I double checked and I can confirm it is removed now:
https://raw.githubusercontent.com/phishfort/phishfort-lists/master/blacklists/domains.json

Kind regards.

**Comment by hiiro74** [comment]
ok will check again in 2 days.
