### ISSUE TITLE
[Legitimate Site Blocked] www.cryptorapgod.wtf

### ISSUE THREAD

**Issue by FOAMLabs** [phishfort/phishfort-lists#772]
https://www.cryptorapgod.wtf/

I am happy to invite one of your team to inspect my code. It is safe and not malicious. We are releasing a basic music product. There is no max supply it is open edition and there is no malicious links in the code. I am confused at why this has happened on two of my projects i have worked on. Can you please take me off your fuzzy list and take the warning off. thanks. 

sincerely,
Larry Klosowski

**Comment by shrestha-milann** [comment]
Hi there,

Sorry for the inconvenience.
We have revoked the listed domain. It will take a few minutes to reflect.

Warm Regards,

Milan Shrestha

Anti-Phishing Operations

***@***.***

phishfort.com <https://www.phishfort.com/>

<https://www.linkedin.com/company/phishfort/>   <https://t.me/phishfort>
<https://twitter.com/PhishFort>
