### ISSUE TITLE
[Legitimate Site Blocked] babydogeswap.com

### ISSUE THREAD

**Issue by bbetsey** [phishfort/phishfort-lists#777]
https://babydogeswap.com/

**Comment by shrestha-milann** [comment]
Hi there,

Sorry for the inconvenience.
We have revoked the listed domain. It will take a few minutes to reflect.

Warm Regards,

Milan Shrestha

Anti-Phishing Operations

***@***.***

phishfort.com <https://www.phishfort.com/>

<https://www.linkedin.com/company/phishfort/>   <https://t.me/phishfort>
<https://twitter.com/PhishFort>
