### ISSUE TITLE
mydukaan.io [#35997] should not be on the blacklist domains.

### ISSUE THREAD

**Issue by Sand33pSrinivasan** [phishfort/phishfort-lists#79]
Please, remove this website from your blacklist, this website is secure and does not cause any damage to it's users. This is an Indian startup that helps the entrepreneur to grow their business with the digital storefront.

Please check the following blog which got published recently about us.
https://techcrunch.com/2022/06/15/indias-dukaan-expands-globally-to-take-on-shopify/

Hope you can remove it from the blacklist (domains.json and hotlist.json)

In domains.json we are listed in the line number #35997
In hotlist.json we are listed in the line number #7195
Our domain is mydukaan.io, Please get it removed.

Thank you for your help.  @javierpignata

Here it is their Privacy Policy: https://mydukaan.io/privacy

**Comment by javierpignata** [comment]
Hi Sandeep.
We removed the domain from our blacklist. Please wait a few hours to let our DB refresh and try again. Let us know if the issue is not solved.
Thanks!

**Comment by Sand33pSrinivasan** [comment]
@javierpignata Thanks for removing it. How much time will your DB take to refresh ?

It's been more than 20 minutes and still opera is showing mydukaan.io as a malicious site.

**Comment by javierpignata** [comment]
Hi Sandeep,

it should be resolved in the next hour.

Kind regards.

**Comment by Sand33pSrinivasan** [comment]
This is fixed, Thanks for your response @javierpignata
