### ISSUE TITLE
website Beacons.ai / beacons.page is safe. it is a website similar to linktree. some users may abuse the service however it is safe otherwise

### ISSUE THREAD

**Issue by joejoe135791** [phishfort/phishfort-lists#84]

**Comment by javierpignata** [comment]
Hi Joe,
Many thanks for reporting.
We removed the platform from our blacklist. Please allow some hours before the DB is updated and try again.
Let us know if the issue persists.

Kind regards.

**Comment by MiChaelinzo** [comment]
I agree I got my beacons.ai/cyberworld banned too etc. and I'm a frequent user of Opera GX this is my main browser...

**Comment by joejoe135791** [comment]
> I agree I got my beacons.ai/cyberworld banned too etc. and I'm a frequent user of Opera GX this is my main browser... 

I use opera GX too and my beacons page was blocked as well
