### ISSUE TITLE
[Legitimate Site Blocked] www.formpl.us

### ISSUE THREAD

**Issue by alhassanmoses** [phishfort/phishfort-lists#876]
https://www.formpl.us/

**Comment by shrestha-milann** [comment]
HI there,

We have removed it from our blacklist. It will take a few minutes to
reflect.

Warm Regards,

Milan Shrestha

Anti-Phishing Operations

***@***.***

phishfort.com <https://www.phishfort.com/>

<https://www.linkedin.com/company/phishfort/>   <https://t.me/phishfort>
<https://twitter.com/PhishFort>

**Comment by alhassanmoses** [comment]
Thanks for the swift response.
