### ISSUE TITLE
[Legitimate Site Blocked] dappgate.app

### ISSUE THREAD

**Issue by cozfuttu** [phishfort/phishfort-lists#884]
Hello, our community is still reporting "Deceptive site ahead" flag. It looks like users entering the website for the first time are getting the warning, while users entered before don't seem to get it. Could you please check? Thanks in advance.

**Comment by shrestha-milann** [comment]
Hi,

The domain had already been delisted. Please clear the cache of the browser.

Warm Regards,

Milan Shrestha

Anti-Phishing Operations

***@***.***

phishfort.com <https://www.phishfort.com/>

<https://www.linkedin.com/company/phishfort/>   <https://t.me/phishfort>
<https://twitter.com/PhishFort>

**Comment by cozfuttu** [comment]
Like I said, users entering the website for the first time are getting the warning, so it shouldn't be a cache problem. I just tried entering the website on a fresh browser and I got the warning again.

**Comment by shrestha-milann** [comment]
Hi,

Understood.
The issue has been resolved from our end. Please advise the users to clear
the cache.
You may confirm the delisting of domain from here:
https://lookup.phishfort.com/api/lookup?domain=dappgate.app

Warm Regards,

Milan Shrestha

Anti-Phishing Operations

***@***.***

phishfort.com <https://www.phishfort.com/>

<https://www.linkedin.com/company/phishfort/>   <https://t.me/phishfort>
<https://twitter.com/PhishFort>

**Comment by cozfuttu** [comment]
Okay, thank you.
