### ISSUE TITLE
[Legitimate Site Blocked] basedswap.exchange

### ISSUE THREAD

**Issue by MadCultish** [phishfort/phishfort-lists#897]
https://basedswap.exchange/

This is a legitimate website with a fully functional DEX. It's likely a competitor reported this website in order to hurt this project. Please remove the warning asap.

**Comment by shrestha-milann** [comment]
Hello,

Thanks for the heads up.
We have removed it from the blocklist. It will take a few minutes to
reflect. If the issue persists, please let us know.

Warm Regards,

Milan Shrestha

Anti-Phishing Operations

***@***.***

phishfort.com <https://www.phishfort.com/>

<https://www.linkedin.com/company/phishfort/>   <https://t.me/phishfort>
<https://twitter.com/PhishFort>

**Comment by Cryptoarubaa** [comment]
It’s still not fixed? Can anyone fix this asap as it’s hurting our project with this fake flag.

**Comment by Cryptoarubaa** [comment]
> Hello, Thanks for the heads up. We have removed it from the blocklist. It will take a few minutes to reflect. If the issue persists, please let us know. Warm Regards, Milan Shrestha Anti-Phishing Operations ***@***.*** phishfort.com <https://www.phishfort.com/> <https://www.linkedin.com/company/phishfort/> <https://t.me/phishfort> <https://twitter.com/PhishFort>
> […](#)

This is still not working?
Can anyone do this asap?
Thank you
