### ISSUE TITLE
[Urgent][Legitimate Site Blocked] platform.spotonchain.ai

### ISSUE THREAD

**Issue by bbminhtri** [phishfort/phishfort-lists#968]
**We are in the middle of our Beta launch when our users got blocked, so any quick help is greatly appreciated!**

https://spotonchain.ai
https://platform.spotonchain.ai

About spotonchain:
Spot On Chain is a pioneering platform designed to simplify on-chain data analysis and provide accessible insights for all in the cryptocurrency space. Our AI-powered platform offers easily digestible insights, intuitive visualizations, AI assistance, one-click alerts, and mobile accessibility. Our aim is to make on-chain data usable and comprehensible to a wide range of users, regardless of their technical background, ensuring confident decision-making in the cryptocurrency market.

Twitter: https://twitter.com/spotonchain
Website: https://spotonchain.ai/

**Comment by bbminhtri** [comment]
Please help to review if you have time @shrestha-milann @milannshrestha 
Metamask is depending on this list of yours: https://github.com/phishfort/phishfort-lists/blob/b5e86586d6264474ac03064d6309a9e3811a80d2/blacklists/hotlist.json#L6594

**Comment by Deon-Trevor** [comment]
Hi there. From what I can tell your platforms seem to not be on our blacklist as you can see here:

https://lookup.phishfort.com/api/lookup?url=https://spotonchain.ai/
https://lookup.phishfort.com/api/lookup?url=https://platform.spotonchain.ai/

**Comment by bbminhtri** [comment]
Thank you, it seems it was removed from the hotlist, not sure why it was added earlier? (https://github.com/phishfort/phishfort-lists/blob/b5e86586d6264474ac03064d6309a9e3811a80d2/blacklists/hotlist.json#L6594)

We will proceed to inform Metamask in this case.

**Comment by bbminhtri** [comment]
Is it possible to add our domain into your whitelist @Deon-Trevor?

**Comment by Deon-Trevor** [comment]
That is possible. Right on it!
